services:
  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_HOST=https://shiny-engine-r44695gjpjw5cprv4-4500.app.github.dev
      - FLOCI_HOST=https://shiny-engine-r44695gjpjw5cprv4-4566.app.github.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock